basePath: /
definitions:
  CreateCatRequest:
    properties:
      color:
        type: string
      name:
        type: string
    type: object
  entity.Cat:
    properties:
      color:
        example: Black
        type: string
      id:
        example: 8d6dde41-d23a-49a5-a9d7-6cbba52ec7fc
        type: string
      name:
        example: Ryuk
        type: string
    type: object
host: localhost:8050
info:
  contact:
    name: API Support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/cat:
    get:
      consumes:
      - application/json
      description: finds all the cats
      operationId: find-all-cats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/entity.Cat'
            type: array
      summary: Finds all the cats
    post:
      consumes:
      - application/json
      description: creates a cat
      operationId: create-cat
      parameters:
      - description: Cat parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/CreateCatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Cat'
      summary: Creates a cat
  /v1/cat/{id}:
    get:
      consumes:
      - application/json
      description: get cat by id
      operationId: get-cat-by-id
      parameters:
      - description: Cat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Cat'
      summary: Finds a cat by its id
swagger: "2.0"
